/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.bonus;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.Collections;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/**
 *
 * @author anaju
 */
public class frGerenciador extends javax.swing.JFrame {

    /**
     * Creates new form Gerenciador
     */
    public frGerenciador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNovoNumero = new javax.swing.JTextField();
        btnAdiconar = new javax.swing.JButton();
        lbNumeros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLista = new javax.swing.JTextArea();
        btnListar = new javax.swing.JButton();
        btnPar = new javax.swing.JButton();
        btnImpar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        painel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbMax = new javax.swing.JLabel();
        lbMin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbMedia = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnDeletar1 = new javax.swing.JButton();
        lbTotal1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Adicionar novo numero:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtNovoNumero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNovoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNovoNumeroActionPerformed(evt);
            }
        });
        txtNovoNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNovoNumeroKeyPressed(evt);
            }
        });
        jPanel1.add(txtNovoNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 114, -1));

        btnAdiconar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAdiconar.setText("Adicionar");
        btnAdiconar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdiconarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdiconar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        lbNumeros.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNumeros.setForeground(new java.awt.Color(0, 0, 204));
        lbNumeros.setText("Numeros:");
        jPanel1.add(lbNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txtLista.setBackground(new java.awt.Color(210, 238, 248));
        txtLista.setColumns(20);
        txtLista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtLista.setRows(5);
        jScrollPane1.setViewportView(txtLista);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 460, 125));

        btnListar.setBackground(new java.awt.Color(102, 204, 255));
        btnListar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnListar.setText("Listar N°");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jPanel1.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 90, -1));

        btnPar.setBackground(new java.awt.Color(102, 204, 255));
        btnPar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPar.setText("Listar Pares");
        btnPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParActionPerformed(evt);
            }
        });
        jPanel1.add(btnPar, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 360, 110, -1));

        btnImpar.setBackground(new java.awt.Color(102, 204, 255));
        btnImpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnImpar.setText("Listar Impares");
        btnImpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImparActionPerformed(evt);
            }
        });
        jPanel1.add(btnImpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        btnAtualizar.setBackground(new java.awt.Color(102, 204, 255));
        btnAtualizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAtualizar.setText("Atualizar N°");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        btnDeletar.setBackground(new java.awt.Color(102, 204, 255));
        btnDeletar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDeletar.setText("Deletar N°");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        btnOrdenar.setBackground(new java.awt.Color(51, 153, 255));
        btnOrdenar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        painel.setBackground(new java.awt.Color(185, 231, 255));
        painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("jLabel9");
        painel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        lbMax.setText("0");
        painel.add(lbMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        lbMin.setText("0");
        painel.add(lbMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Média: ");
        painel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("min:");
        painel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Max:");
        painel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        lbMedia.setBackground(new java.awt.Color(0, 0, 0));
        lbMedia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbMedia.setText("0");
        painel.add(lbMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 90, -1));

        jPanel1.add(painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 490, 30));

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        txtBuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });
        jPanel3.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 87, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Buscar números:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 110));

        btnDeletar1.setBackground(new java.awt.Color(102, 204, 255));
        btnDeletar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDeletar1.setText("Limpar");
        btnDeletar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeletar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 80, -1));

        lbTotal1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbTotal1.setForeground(new java.awt.Color(0, 0, 204));
        lbTotal1.setText("0");
        jPanel1.add(lbTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 400));

        jLabel4.setText("p");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 411, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 411, -1, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 411, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 GerenciadorNumeros gn = new GerenciadorNumeros();

    private void btnAdiconarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdiconarActionPerformed

        int add = Integer.parseInt(txtNovoNumero.getText());

        if (txtNovoNumero.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira o número, por favor.");
        } else {
            gn.adicionar(add);
            JOptionPane.showMessageDialog(null, "Número adicionado com sucesso!");
            txtNovoNumero.requestFocus();
            txtNovoNumero.setText(null);
            btnListar.doClick();
        }

        //total de elementos
        int tamanho = gn.numero.size();
        String total = Integer.toString(tamanho);
        lbTotal1.setText(total);

        //media
        DecimalFormat f = new DecimalFormat("0.0");
        String n = f.format(gn.calcularMedia());
        lbMedia.setText(n);

        //max
        int max = Collections.max(gn.numero);
        String maior = Integer.toString(max);
        lbMax.setText(maior);

        //min
        int min = Collections.min(gn.numero);
        String menor = Integer.toString(min);
        lbMin.setText(menor);

    }//GEN-LAST:event_btnAdiconarActionPerformed

    private void txtNovoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovoNumeroActionPerformed

    }//GEN-LAST:event_txtNovoNumeroActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        txtLista.setText(gn.listar());
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        btnListar.doClick();
        int cod;
        String novoElemento;
        cod = Integer.parseInt(JOptionPane.showInputDialog("Informe o código abaixo:"));
        novoElemento = JOptionPane.showInputDialog("Novo Número:");
        int novo = Integer.parseInt(novoElemento);
        gn.alterar((cod - 1), novo);
        btnListar.doClick();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        Collections.sort(gn.numero);
        btnListar.doClick();
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        btnListar.doClick();
        int cod;
        cod = Integer.parseInt(JOptionPane.showInputDialog(null, "Informe o código abaixo:"));
        if (JOptionPane.showConfirmDialog(null, "tem certeza de que deseja deletar?", "Confirme:",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            gn.excluir(cod - 1);
        } else {
            JOptionPane.showMessageDialog(null, "Exclusão cancelada com sucesso!");
        }
        btnListar.doClick();
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void txtNovoNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNovoNumeroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAdiconar.doClick();
        }
    }//GEN-LAST:event_txtNovoNumeroKeyPressed

    private void btnDeletar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletar1ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir tudo?", "Confirme:",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            gn.numero.clear();
            lbTotal1.setText("0");
            lbMedia.setText("0");
            lbMax.setText("0");
            lbMin.setText("0");
        } else {
            JOptionPane.showMessageDialog(null, "Exclusão cancelada com sucesso!");
        }
        btnListar.doClick();
    }//GEN-LAST:event_btnDeletar1ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        int n = Integer.parseInt(txtBuscar.getText());

        int contagem = Collections.frequency(gn.numero, n);

        if (txtBuscar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira um número para pesquisa.");
        } else {
            JOptionPane.showMessageDialog(null, "O número: " + n
                    + " está presente na lista " + contagem + " vezes");
        }

    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnBuscar.doClick();
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void btnParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParActionPerformed
        String numerosPares = gn.numero.stream()
                .filter(numero -> numero % 2 == 0)
                .map(String::valueOf)
                .collect(Collectors.joining("\n"));
        txtLista.setText(numerosPares);
    }//GEN-LAST:event_btnParActionPerformed

    private void btnImparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImparActionPerformed
        String numerosImpares = gn.numero.stream()
                .filter(numero -> numero % 2 != 0)
                .map(String::valueOf)
                .collect(Collectors.joining("\n"));
        txtLista.setText(numerosImpares);

    }//GEN-LAST:event_btnImparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frGerenciador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdiconar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnDeletar1;
    private javax.swing.JButton btnImpar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnPar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMax;
    private javax.swing.JLabel lbMedia;
    private javax.swing.JLabel lbMin;
    private javax.swing.JLabel lbNumeros;
    private javax.swing.JLabel lbTotal1;
    private javax.swing.JPanel painel;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtLista;
    private javax.swing.JTextField txtNovoNumero;
    // End of variables declaration//GEN-END:variables
}
